// Code generated by genx:code DO NOT EDIT.
package schex

import (
	"fmt"
)

func (e Error) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[schex.Error:%d] unknown", e)
	case ERROR_UNDEFINED:
		return "[schex.Error:0] undefined"
	case ERROR__REACH_MAX_PENDING:
		return "[schex.Error:1] reached max pending limitation"
	case ERROR__SCHEDULER_RERUN:
		return "[schex.Error:2] scheduler is already running"
	case ERROR__SCHEDULER_CANCELED:
		return "[schex.Error:3] scheduler is manual canceled"
	case ERROR__SCHEDULER_JOB_PANICKED:
		return "[schex.Error:4] scheduler job panicked"
	}
}
