// Code generated by genx:code DO NOT EDIT.
package synapse

import (
	"fmt"
)

func (e Error) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[synapse.Error:%d] unknown", e)
	case ERROR_UNDEFINED:
		return "[synapse.Error:0] undefined"
	case ERROR__SYNAPSE_CLOSED:
		return "[synapse.Error:1] SYNAPSE_CLOSED"
	case ERROR__SYNAPSE_CLOSE_TIMEOUT:
		return "[synapse.Error:2] SYNAPSE_CLOSE_TIMEOUT"
	}
}
